langauge: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=HEAD

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install --deps search-auto $TRAVIS_BUILD_DIR/tools/benchmark-util
  - raco pkg install --deps search-auto $TRAVIS_BUILD_DIR/tools/summarize
  - raco pkg install --deps search-auto $TRAVIS_BUILD_DIR/tools/diagnose

script:
  - raco test $TRAVIS_BUILD_DIR/tools
  - raco test $TRAVIS_BUILD_DIR/tools/run-test.rkt
  - raco setup --check-pkg-deps benchmark-util
  - raco setup --check-pkg-deps gtp-summarize
  - raco setup --check-pkg-deps gtp-diagnose
